[workspace]
members = [
    "fvm",
    "sdk",
    "shared",
    "actors/*",
    "examples/actor",
    "testing/conformance",
    "ipld/*",
]
exclude = []

default-members = [
    "fvm",
    "sdk",
    "shared",
    "actors/*",
    "testing/conformance",
    "ipld/*"
    # don't build the examples by default, as they require a specific target and profile.
    # build them with cargo make examples
    # "examples/*"
]

[profile.actor]
inherits = "release"
panic = "abort"
overflow-checks = true
lto = true
opt-level = "z"
#strip = true
